CREATE TABLE analysis_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_name VARCHAR(64) NOT NULL,
    status VARCHAR(64) NOT NULL,
    progress INT DEFAULT 0,
    input_path CLOB,
    output_path CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    error_message CLOB,
    worker_id VARCHAR(128),
    device VARCHAR(128)
);

CREATE TABLE cac_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL,
    agatston_score NUMERIC(12, 2),
    risk_grade VARCHAR(32),
    result_json_path CLOB,
    ct_volume_path CLOB,
    ai_mask_path CLOB,
    corrected_mask_path CLOB,
    corrected_agatston_score NUMERIC(12, 2),
    corrected_risk_grade VARCHAR(32),
    corrected_result_json_path CLOB,
    corrected_at TIMESTAMP,
    report_path CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cac_results_job
        FOREIGN KEY (job_id) REFERENCES analysis_jobs(id) ON DELETE CASCADE,
    CONSTRAINT uk_cac_results_job_id UNIQUE (job_id)
);

CREATE TABLE corrected_mask_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL,
    version INT NOT NULL,
    mask_path CLOB NOT NULL,
    metadata_path CLOB NOT NULL,
    checksum_sha256 VARCHAR(64),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_corrected_mask_versions_job
        FOREIGN KEY (job_id) REFERENCES analysis_jobs(id) ON DELETE CASCADE,
    CONSTRAINT uk_corrected_mask_versions_job_version UNIQUE (job_id, version)
);
